# be
debug: False
  # False
training: True


ctrl:
  # MODE:开启视频(video)/相机(camera)
  # RECORDING:是否录制预测结果视频
  # SENDING:发送小地图信息(开启子线程)
  # SAVE:隔30帧保存图片(原图 + 结果图)
  MODE: 'video'
  DETECT: True
  LAST_ARMOR: True
  RECORDING: False
  HIGHWAY: False
  GUI: True
  ANCHOR: True

  SENDING: True
  RECEIVING: False

  MAP: False
  ALARM: False
  CALIB: False

  FILE_READ: False
  FILE_WRITE: False
  SAVE_CSV: False
  SAVE_IMG: False

  CHESSBOARD: False

zone:
  LOAD_ZONE: True
  SAVE_ZONE: False

video_left: 'D:\useful\video_record5-25-16-40-2-3\raw\left\raw_left01.mp4'
video_right: 'D:\useful\video_record5-25-16-40-2-3\raw\right\raw_right.mp4'

#red enemy------------------------------------
#
#
#---------------------------------------------

# './weights/yolov8/with_sod_yolov8l_epoch140_16_640_adam_half_0705_.pt'
# './weights/yolov8/best0427_74epoch.pt'

weights:
  yolov8: './weights/yolov8/0720_without_class_5_1280_SGD_epoch126_best.pt'
  # './weights/yolov8/0718_without_class_5_1280_SGD_epoch44.pt'
  # './weights/yolov8/with_sod_epoch64_yolov8m_1280.pt'
  # './weights/yolov8/with_sod_yolov8s_epoch50_1280.pt'
  # './weights/yolov8/with_sod_yolov8l_epoch140_16_640_adam_half_0705_.pt'
  #'./weights/yolov8/best_7_16_1280.pt'
  # './weights/yolov8/with_sod_yolov8l_epoch140_16_640_adam_half_0705_.pt'
  # car: './weights/l_no_extra.pt'
  # armor: './weights/100.pth'

ui:
  image_w: 1280
  image_h: 640