# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 1080)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QGraphicsView(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(285, 0, 1350, 1080))
        self.image.setObjectName("image")
        self.enemypost = QtWidgets.QProgressBar(self.centralwidget)
        self.enemypost.setGeometry(QtCore.QRect(20, 210, 256, 30))
        self.enemypost.setAutoFillBackground(False)
        self.enemypost.setMaximum(1500)
        self.enemypost.setProperty("value", 1500)
        self.enemypost.setAlignment(QtCore.Qt.AlignCenter)
        self.enemypost.setObjectName("enemypost")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 190, 256, 25))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(20, 280, 256, 25))
        self.textEdit_5.setObjectName("textEdit_5")
        self.enemywatch = QtWidgets.QProgressBar(self.centralwidget)
        self.enemywatch.setGeometry(QtCore.QRect(20, 300, 256, 30))
        self.enemywatch.setMaximum(600)
        self.enemywatch.setProperty("value", 600)
        self.enemywatch.setAlignment(QtCore.Qt.AlignCenter)
        self.enemywatch.setObjectName("enemywatch")
        self.time = QtWidgets.QTimeEdit(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(10, 20, 271, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(79)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.time.setFont(font)
        self.time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time.setStyleSheet("")
        self.time.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.time.setSpecialValueText("")
        self.time.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 7, 0)))
        self.time.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.time.setObjectName("time")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1680, 20, 201, 31))
        self.pushButton.setObjectName("pushButton")
        self.Text = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text.setGeometry(QtCore.QRect(710, 10, 500, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        self.Text.setFont(font)
        self.Text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Text.setStyleSheet("")
        self.Text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Text.setReadOnly(False)
        self.Text.setObjectName("Text")
        self.textEdit_10 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_10.setGeometry(QtCore.QRect(20, 750, 256, 25))
        self.textEdit_10.setObjectName("textEdit_10")
        self.textEdit_16 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_16.setGeometry(QtCore.QRect(20, 570, 256, 25))
        self.textEdit_16.setObjectName("textEdit_16")
        self.enemy4 = QtWidgets.QProgressBar(self.centralwidget)
        self.enemy4.setGeometry(QtCore.QRect(20, 680, 256, 30))
        self.enemy4.setProperty("value", 100)
        self.enemy4.setAlignment(QtCore.Qt.AlignCenter)
        self.enemy4.setObjectName("enemy4")
        self.enemy3 = QtWidgets.QProgressBar(self.centralwidget)
        self.enemy3.setGeometry(QtCore.QRect(20, 590, 256, 30))
        self.enemy3.setProperty("value", 100)
        self.enemy3.setAlignment(QtCore.Qt.AlignCenter)
        self.enemy3.setObjectName("enemy3")
        self.enemy1 = QtWidgets.QProgressBar(self.centralwidget)
        self.enemy1.setGeometry(QtCore.QRect(20, 410, 256, 30))
        self.enemy1.setMaximum(150)
        self.enemy1.setProperty("value", 150)
        self.enemy1.setAlignment(QtCore.Qt.AlignCenter)
        self.enemy1.setObjectName("enemy1")
        self.textEdit_17 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_17.setGeometry(QtCore.QRect(20, 390, 256, 25))
        self.textEdit_17.setObjectName("textEdit_17")
        self.enemy5 = QtWidgets.QProgressBar(self.centralwidget)
        self.enemy5.setGeometry(QtCore.QRect(20, 770, 256, 30))
        self.enemy5.setProperty("value", 100)
        self.enemy5.setAlignment(QtCore.Qt.AlignCenter)
        self.enemy5.setObjectName("enemy5")
        self.textEdit_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_8.setGeometry(QtCore.QRect(20, 660, 256, 25))
        self.textEdit_8.setObjectName("textEdit_8")
        self.our5 = QtWidgets.QProgressBar(self.centralwidget)
        self.our5.setGeometry(QtCore.QRect(1650, 770, 256, 30))
        self.our5.setProperty("value", 100)
        self.our5.setAlignment(QtCore.Qt.AlignCenter)
        self.our5.setObjectName("our5")
        self.ourwatch = QtWidgets.QProgressBar(self.centralwidget)
        self.ourwatch.setGeometry(QtCore.QRect(1650, 300, 256, 30))
        self.ourwatch.setMaximum(600)
        self.ourwatch.setProperty("value", 600)
        self.ourwatch.setAlignment(QtCore.Qt.AlignCenter)
        self.ourwatch.setObjectName("ourwatch")
        self.textEdit_18 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_18.setGeometry(QtCore.QRect(1650, 570, 256, 25))
        self.textEdit_18.setObjectName("textEdit_18")
        self.textEdit_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_12.setGeometry(QtCore.QRect(1650, 750, 256, 25))
        self.textEdit_12.setObjectName("textEdit_12")
        self.our1 = QtWidgets.QProgressBar(self.centralwidget)
        self.our1.setGeometry(QtCore.QRect(1650, 410, 256, 30))
        self.our1.setMaximum(150)
        self.our1.setProperty("value", 150)
        self.our1.setAlignment(QtCore.Qt.AlignCenter)
        self.our1.setObjectName("our1")
        self.textEdit_15 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_15.setGeometry(QtCore.QRect(1650, 190, 256, 25))
        self.textEdit_15.setObjectName("textEdit_15")
        self.ourpost = QtWidgets.QProgressBar(self.centralwidget)
        self.ourpost.setGeometry(QtCore.QRect(1650, 210, 256, 30))
        self.ourpost.setAutoFillBackground(False)
        self.ourpost.setMaximum(1500)
        self.ourpost.setProperty("value", 1500)
        self.ourpost.setAlignment(QtCore.Qt.AlignCenter)
        self.ourpost.setObjectName("ourpost")
        self.textEdit_19 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_19.setGeometry(QtCore.QRect(1650, 280, 256, 25))
        self.textEdit_19.setObjectName("textEdit_19")
        self.our3 = QtWidgets.QProgressBar(self.centralwidget)
        self.our3.setGeometry(QtCore.QRect(1650, 590, 256, 30))
        self.our3.setProperty("value", 100)
        self.our3.setAlignment(QtCore.Qt.AlignCenter)
        self.our3.setObjectName("our3")
        self.textEdit_20 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_20.setGeometry(QtCore.QRect(1650, 390, 256, 25))
        self.textEdit_20.setObjectName("textEdit_20")
        self.our4 = QtWidgets.QProgressBar(self.centralwidget)
        self.our4.setGeometry(QtCore.QRect(1650, 680, 256, 30))
        self.our4.setProperty("value", 100)
        self.our4.setAlignment(QtCore.Qt.AlignCenter)
        self.our4.setObjectName("our4")
        self.textEdit_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_21.setGeometry(QtCore.QRect(1650, 660, 256, 25))
        self.textEdit_21.setObjectName("textEdit_21")
        self.enemy2 = QtWidgets.QProgressBar(self.centralwidget)
        self.enemy2.setGeometry(QtCore.QRect(20, 500, 256, 30))
        self.enemy2.setMaximum(500)
        self.enemy2.setProperty("value", 500)
        self.enemy2.setAlignment(QtCore.Qt.AlignCenter)
        self.enemy2.setObjectName("enemy2")
        self.textEdit_22 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_22.setGeometry(QtCore.QRect(20, 480, 256, 25))
        self.textEdit_22.setObjectName("textEdit_22")
        self.our2 = QtWidgets.QProgressBar(self.centralwidget)
        self.our2.setGeometry(QtCore.QRect(1650, 500, 256, 30))
        self.our2.setMaximum(500)
        self.our2.setProperty("value", 500)
        self.our2.setAlignment(QtCore.Qt.AlignCenter)
        self.our2.setObjectName("our2")
        self.textEdit_23 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_23.setGeometry(QtCore.QRect(1650, 480, 256, 25))
        self.textEdit_23.setObjectName("textEdit_23")
        self.enemybase = QtWidgets.QProgressBar(self.centralwidget)
        self.enemybase.setGeometry(QtCore.QRect(20, 890, 256, 30))
        self.enemybase.setMaximum(5000)
        self.enemybase.setProperty("value", 5000)
        self.enemybase.setAlignment(QtCore.Qt.AlignCenter)
        self.enemybase.setObjectName("enemybase")
        self.textEdit_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_11.setGeometry(QtCore.QRect(20, 870, 256, 25))
        self.textEdit_11.setObjectName("textEdit_11")
        self.textEdit_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_13.setGeometry(QtCore.QRect(1650, 870, 256, 25))
        self.textEdit_13.setObjectName("textEdit_13")
        self.ourbase = QtWidgets.QProgressBar(self.centralwidget)
        self.ourbase.setGeometry(QtCore.QRect(1650, 890, 256, 30))
        self.ourbase.setMaximum(5000)
        self.ourbase.setProperty("value", 5000)
        self.ourbase.setAlignment(QtCore.Qt.AlignCenter)
        self.ourbase.setObjectName("ourbase")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enemypost.setFormat(_translate("MainWindow", "%v/1500"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">敌方前哨站</span></p></body></html>"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">敌方哨兵</span></p></body></html>"))
        self.enemywatch.setFormat(_translate("MainWindow", "%v/600"))
        self.time.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.pushButton.setText(_translate("MainWindow", "退出"))
        self.Text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Devanagari\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">敌方步兵5</span></p></body></html>"))
        self.textEdit_16.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">敌方步兵3</span></p></body></html>"))
        self.enemy4.setFormat(_translate("MainWindow", "%v"))
        self.enemy3.setFormat(_translate("MainWindow", "%v"))
        self.enemy1.setFormat(_translate("MainWindow", "%v"))
        self.textEdit_17.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">敌方英雄1</span></p></body></html>"))
        self.enemy5.setFormat(_translate("MainWindow", "%v"))
        self.textEdit_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">敌方步兵4</span></p></body></html>"))
        self.our5.setFormat(_translate("MainWindow", "%v"))
        self.ourwatch.setFormat(_translate("MainWindow", "%v/600"))
        self.textEdit_18.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">我方步兵3</span></p></body></html>"))
        self.textEdit_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">我方步兵5</span></p></body></html>"))
        self.our1.setFormat(_translate("MainWindow", "%v"))
        self.textEdit_15.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">我方前哨站</span></p></body></html>"))
        self.ourpost.setFormat(_translate("MainWindow", "%v/1500"))
        self.textEdit_19.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">我方哨兵</span></p></body></html>"))
        self.our3.setFormat(_translate("MainWindow", "%v"))
        self.textEdit_20.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">我方英雄1</span></p></body></html>"))
        self.our4.setFormat(_translate("MainWindow", "%v"))
        self.textEdit_21.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">我方步兵4</span></p></body></html>"))
        self.enemy2.setFormat(_translate("MainWindow", "%v"))
        self.textEdit_22.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">敌方工程2</span></p></body></html>"))
        self.our2.setFormat(_translate("MainWindow", "%v"))
        self.textEdit_23.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">我方工程2</span></p></body></html>"))
        self.enemybase.setFormat(_translate("MainWindow", "%v/%m"))
        self.textEdit_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">敌方基地</span></p></body></html>"))
        self.textEdit_13.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">我方基地</span></p></body></html>"))
        self.ourbase.setFormat(_translate("MainWindow", "%v/%m"))
